config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index] do
    member do
      get 'approve_recruiter/:recruiter_id', to: 'admin#approve_recruiter', as: 'approve_recruiter'
      get 'destroy_recruiter/:recruiter_id', to: 'admin#destroy_recruiter', as: 'destroy_recruiter'
    end
  end
  resources :companies
  get 'my_company', to: 'companies#my_company', as: :my_company

  root 'home#index'

  devise_for :users

  resources :jobs, shallow: true do
    resources :assessments, shallow: true do
      resources :questions, shallow: true
    end

    resources :applications, controller: 'job_applications' do
      member do
        get 'change_status/:status', to: 'job_applications#change_status', as: 'change_status'
      end

      resources :participations
    end
  end

  get "my_jobs", to: "jobs#my_jobs", as: "my_jobs"
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :application
  belongs_to :assessment
  has_many :submissions, dependent: :destroy
  accepts_nested_attributes_for :submissions, allow_destroy: true
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_action :set_participation, only: %i[ show edit update destroy ]
  before_action :set_application, only: %i[ new create ]
  before_action :check_assessment_time, only: %i[ new ]
  before_action :set_questions, only: %i[ new create ]

  def index
    @participations = Participation.all
  end

  def show
  end

  def new
    @participation = @application.build_participation
    @questions.each do |question|
      submission = @participation.submissions.build(question_id: question.id)
      question.answers.each do |answer|
        submission.responses.build(answer_id: answer.id)
      end
    end
  end

  def edit
  end

  def create
    @participation = @application.build_participation(participation_params)

    respond_to do |format|
      if @participation.save
        CalculateScoreJob.perform_now(@participation.id)
        format.html { redirect_to application_url(@participation.application), notice: "Your submission has been recorded successfully." }
        format.json { render :show, status: :created, location: @participation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @participation.update(participation_params)
        format.html { redirect_to participation_url(@participation), notice: "Participation was successfully updated." }
        format.json { render :show, status: :ok, location: @participation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @participation.destroy!

    respond_to do |format|
      format.html { redirect_to participations_url, notice: "Participation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_participation
    @participation = Participation.find(params[:id])
  end

  def set_application
    @application = Application.find(params[:application_id])
  end

  def set_questions
    @questions = @assessment.questions.includes(:answers)
  end

  def participation_params
    params.require(:participation).permit(
      :application_id, :assessment_id,
      submissions_attributes: [
        :id, :question_id, :_destroy,
        responses_attributes: [:id, :answer_id, :correct, :_destroy]
      ]
    )
  end

  def check_assessment_time
    check_starting_time
    check_ending_time
  end

  def check_starting_time
    if Time.current < @assessment.starting_time
      flash[:alert] = "The assessment hasn't started yet."
      redirect_to application_path(@application)
    end
  end

  def check_ending_time
    if Time.current > @assessment.ending_time
      flash[:alert] = "The assessment has ended."
      redirect_to application_path(@application)
    end
  end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
  def assessment(application)
    application.job.assessment
  end
end

app/views/participations/_form.html.erb
<h3 ><span id="timer" class="badge text-bg-warning"></span></h3>
<%= form_with(model: [@application, participation], id: 'assessment-form') do |form| %>
  <% if participation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(participation.errors.count, "error") %> prohibited this participation from being saved:</h2>

      <ul>
        <% participation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :application_id, value: @application.id %>
  </div>

  <div>
    <%= form.hidden_field :assessment_id, value: assessment(@application).id %>
  </div>

  <% @questions.each do |question| %>
    <%= form.fields_for :submissions, form.object.submissions.build(question_id: question.id) do |submission_field| %>
      <div class="card">
        <div class="card-header">
          <h5><%= question.statement %></h5>
        </div>
        <div class="card-body">
          <% question.answers.each do |answer| %>
            <div class="form-check">
              <%= submission_field.fields_for :responses, submission_field.object.responses.build(answer_id: answer.id) do |response_field| %>
                <%= response_field.hidden_field :answer_id, value: answer.id %>
                <%= response_field.check_box :correct, class: "form-check-input", id: "option_#{response_field.object.answer_id}" %>
                <%= answer.option %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <br>
  <div>
    <%= form.submit "Submit", class: "btn btn-primary", id: "submit-button"%>
  </div>
<% end %>

<script>
    var endTime = new Date('<%= @assessment.ending_time %>').getTime();
</script>

<%= javascript_include_tag 'timer' %>

app/views/participations/_participation.html.erb
<div id="<%= dom_id participation %>">
  <p>
    <strong>Score:</strong>
    <%= participation.score %>
  </p>

  <p>
    <strong>Application:</strong>
    <%= participation.application_id %>
  </p>

  <p>
    <strong>Assessment:</strong>
    <%= participation.assessment_id %>
  </p>

</div>

app/views/participations/edit.html.erb
<h1>Editing participation</h1>

<%= render "form", participation: @participation %>

<br>

<div>
  <%= link_to "Show this participation", @participation %> |
  <%= link_to "Back to participations", participations_path %>
</div>

app/views/participations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Participations</h1>

<div id="participations">
  <% @participations.each do |participation| %>
    <%= render participation %>
    <p>
      <%= link_to "Show this participation", participation %>
    </p>
  <% end %>
</div>

<%= link_to "New participation", new_participation_path %>

app/views/participations/new.html.erb
<h1>Assessment</h1>

<%= render "form", participation: @participation %>

<br>

app/views/participations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @participation %>

<div>
  <%= link_to "Edit this participation", edit_participation_path(@participation) %> |
  <%= link_to "Back to participations", participations_path %>
  <%= button_to "Destroy this participation", @participation, method: :delete %>
</div>