config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index] do
    member do
      get 'approve_recruiter/:recruiter_id', to: 'admin#approve_recruiter', as: 'approve_recruiter'
      get 'destroy_recruiter/:recruiter_id', to: 'admin#destroy_recruiter', as: 'destroy_recruiter'
    end
  end
  resources :companies
  get 'my_company', to: 'companies#my_company', as: :my_company

  root 'home#index'

  devise_for :users

  resources :jobs, shallow: true do
    resources :assessments, shallow: true do
      resources :questions, shallow: true
    end

    resources :applications, controller: 'job_applications' do
      member do
        get 'change_status/:status', to: 'job_applications#change_status', as: 'change_status'
      end

      resources :participations
    end
  end

  get "my_jobs", to: "jobs#my_jobs", as: "my_jobs"
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :job
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true

  has_many :participations, dependent: :destroy

  validates :title, presence: true
  validates :starting_time, presence: true
  validates :ending_time, presence: true
  validate :ending_time_after_starting_time

  private

  def ending_time_after_starting_time
    if starting_time.present? && ending_time.present? && ending_time <= starting_time
      errors.add(:ending_time, "must be after the starting time")
    end
  end
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_job
  before_action :set_assessment, only: %i[ show edit update destroy ]

  # GET /assessments or /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1 or /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = @job.build_assessment
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments or /assessments.json
  def create
    @assessment = @job.build_assessment(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to assessment_url(@assessment), notice: "Assessment was successfully created." }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1 or /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to assessment_url(@assessment), notice: "Assessment was successfully updated." }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1 or /assessments/1.json
  def destroy
    @job = @assessment.job
    @assessment.destroy!

    respond_to do |format|
      format.html { redirect_to job_path(@job), notice: "Assessment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assessment_params
      params.require(:assessment).permit(:title, :starting_time, :ending_time, :candidate_selection, :job_id)
    end

    def set_job
      @job = Job.find_by(id: params[:job_id])
    end
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_assessment.html.erb
<div id="<%= dom_id assessment %>">
  <p>
    <strong>Title:</strong>
    <%= assessment.title %>
  </p>

  <p>
    <strong>Starting time:</strong>
    <%= assessment.starting_time %>
  </p>

  <p>
    <strong>Ending time:</strong>
    <%= assessment.ending_time %>
  </p>

  <p>
    <strong>Candidate selection:</strong>
    <%= assessment.candidate_selection %>
  </p>

  <p>
    <strong>Job:</strong>
    <%= assessment.job_id %>
  </p>

</div>

app/views/assessments/_form.html.erb
<%= form_with(model: [@job, assessment]) do |form| %>
  <% if assessment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(assessment.errors.count, "error") %> prohibited this assessment from being saved:</h2>

      <ul>
        <% assessment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :starting_time, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.datetime_field :starting_time, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :ending_time, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.datetime_field :ending_time, class: "form-control" %>
    </div>
  </div>
  <br>
  <br>
  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/assessments/edit.html.erb
<h1>Editing assessment</h1>

<%= render "form", assessment: @assessment %>

<br>

<div>
  <%= link_to "Show this assessment", @assessment %> |
  <%= link_to "Back to assessments", job_assessments_path(@assessment) %>
</div>

app/views/assessments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Assessments</h1>

<div id="assessments">
  <% @assessments.each do |assessment| %>
    <%= render assessment %>
    <p>
      <%= link_to "Show this assessment", assessment %>
    </p>
  <% end %>
</div>

<%= link_to "New assessment", new_job_assessment_path(@job) %>

app/views/assessments/new.html.erb
<h1>New assessment</h1>

<%= render "form", assessment: @assessment %>

<br>

<div>
  <%#= link_to "Back to assessments", job_assessments_path(@job) %>
  <%= link_to "Back to Job", job_path(@job) %>
</div>

app/views/assessments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @assessment %>

<div class="d-flex">
  <%= link_to "Set Questions", assessment_questions_path(@assessment), method: :get, class: "btn btn-success" %>&nbsp;
  <%= link_to "Edit", edit_assessment_path(@assessment),class: "btn btn-warning" %>&nbsp;
  <%= button_to "Destroy", @assessment, method: :delete, class: "btn btn-danger" %>
</div>