config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index] do
    member do
      get 'approve_recruiter/:recruiter_id', to: 'admin#approve_recruiter', as: 'approve_recruiter'
      get 'destroy_recruiter/:recruiter_id', to: 'admin#destroy_recruiter', as: 'destroy_recruiter'
    end
  end
  resources :companies
  get 'my_company', to: 'companies#my_company', as: :my_company

  root 'home#index'

  devise_for :users

  resources :jobs, shallow: true do
    resources :assessments, shallow: true do
      resources :questions, shallow: true
    end

    resources :applications, controller: 'job_applications' do
      member do
        get 'change_status/:status', to: 'job_applications#change_status', as: 'change_status'
      end

      resources :participations
    end
  end

  get "my_jobs", to: "jobs#my_jobs", as: "my_jobs"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :option, presence: true
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :job
  belongs_to :user

  has_one :participation, dependent: :destroy

  has_one_attached :resume

  validate :correct_resume_mime_type

  enum status: [:applied, :selected, :rejected, :passed]

  private

  def correct_resume_mime_type
    if !resume.attached?
      errors.add(:resume, 'required')
    elsif resume.content_type != 'application/pdf'
      errors.add(:resume, 'must be a PDF')
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :job
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true

  has_many :participations, dependent: :destroy

  validates :title, presence: true
  validates :starting_time, presence: true
  validates :ending_time, presence: true
  validate :ending_time_after_starting_time

  private

  def ending_time_after_starting_time
    if starting_time.present? && ending_time.present? && ending_time <= starting_time
      errors.add(:ending_time, "must be after the starting time")
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user

  has_many :recruiters, -> { where(role: :recruiter) }, class_name: 'User', foreign_key: 'office_id'

  has_many :jobs, dependent: :destroy

  has_one_attached :logo

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :registration_number, presence: true, uniqueness: true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_one :assessment, dependent: :destroy
  belongs_to :company

  has_many :applications, dependent: :destroy

  # Validations
  validates :title, presence: true, length: { minimum: 6 }
  validates :overview, presence: true
  validates :responsibilities, presence: true
  validates :requirements, presence: true
  validates :benifits, presence: true
  validates :location, presence: true
  validates :deadline, presence: true
  validates :salary_range, presence: true
  validate :deadline_cannot_be_in_the_past

  private

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, "can't be in the past")
    end
  end
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :application
  belongs_to :assessment
  has_many :submissions, dependent: :destroy
  accepts_nested_attributes_for :submissions, allow_destroy: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :assessment
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true

  validates :statement, presence: true
  validates_associated :answers
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :submission
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :participation
  has_many :responses, dependent: :destroy
  accepts_nested_attributes_for :responses, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs, dependent: :destroy
  has_one :company, dependent: :destroy
  belongs_to :office, optional: true, class_name: 'Company'

  has_many :applications, dependent: :destroy

  has_one_attached :avatar

  enum role: [:admin, :recruiter, :candidate]

  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates :role, presence: true
  before_save :set_is_verified

  private

  def set_is_verified
    self.is_verified = true unless role == "recruiter"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :set_company, only: %i[ create ]

  # GET /jobs or /jobs.json
  def index
    @pagy, @jobs = pagy(Job.all)
  end

  def my_jobs
    @pagy, @jobs = pagy(Job.where(user_id: current_user.id))
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.build
    @job.company = @company
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = current_user.jobs.build(job_params)
    @job.company = @company

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy!

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :overview, :responsibilities, :requirements, :benifits, :location, :deadline, :salary_range)
    end

    def set_company
      @company = Company.find(current_user.office_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def has_applied(job)
    job.applications.find_by(user_id: current_user.id)
  end

  def can_apply?(job)
    job.deadline > Time.now and current_user.candidate?
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def options(question)
    question.answers.to_a
  end
end

app/views/admin/index.html.erb
<h1>Manage Recruiters</h1>

<table class="table table-striped-columns">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @recruiters.each do |recruiter| %>
      <tr>
        <td><%= recruiter.name %></td>
        <td><%= recruiter.email %></td>
        <td class="d-flex">
          <% if !recruiter.is_verified %>
            <%= link_to "Approve", approve_recruiter_admin_path(current_user, recruiter), method: :get, class: "btn btn-success btn-sm" %>&nbsp;
          <% end %>
          <%= link_to "Delete", destroy_recruiter_admin_path(current_user, recruiter), method: :get, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <b><%= link_to "WellRecruit", root_path, class: "navbar-brand"%></b>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>

        <li class="nav-item">
          <%= link_to "Jobs", jobs_path, method: :get, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Companies", companies_path, method: :get, class: "nav-link"  %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.avatar.attached? %>
                <%= image_tag url_for(current_user.avatar), style: "border-radius: 50%; height: 40px; width: 40px" %>
              <% else %>
                <b>hello <%= current_user.name %></b>
              <% end %>
            </a>
            <ul class="dropdown-menu">
              <%= render 'layouts/role_based_dropdown' %>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path, method: :get, class: "dropdown-item" %></li>
              <li><%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", user_session_path, method: :get, class: "btn btn-outline-primary" %>
          </li> &nbsp;
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, method: :get, class: "btn btn-outline-secondary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_role_based_dropdown.html.erb
<% if current_user.admin? %>
  <%= link_to "Manage Company", my_company_path, method: :get, class: "dropdown-item" %>
  <%= link_to "Manage Recruiters", admin_index_path, method: :get, class: "dropdown-item" %>
<% elsif current_user.recruiter?%>
  <%= link_to "My Jobs", my_jobs_path, method: :get, class: "dropdown-item" %>
<% elsif current_user.candidate? %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WellRecruit</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
  <%= javascript_importmap_tags %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>

<body>
<%= render "layouts/navbar" %>
<br>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>