config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index] do
    member do
      get 'approve_recruiter/:recruiter_id', to: 'admin#approve_recruiter', as: 'approve_recruiter'
      get 'destroy_recruiter/:recruiter_id', to: 'admin#destroy_recruiter', as: 'destroy_recruiter'
    end
  end
  resources :companies
  get 'my_company', to: 'companies#my_company', as: :my_company

  root 'home#index'

  devise_for :users

  resources :jobs, shallow: true do
    resources :assessments, shallow: true do
      resources :questions, shallow: true
    end

    resources :applications, controller: 'job_applications' do
      member do
        get 'change_status/:status', to: 'job_applications#change_status', as: 'change_status'
      end

      resources :participations
    end
  end

  get "my_jobs", to: "jobs#my_jobs", as: "my_jobs"
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_one :assessment, dependent: :destroy
  belongs_to :company

  has_many :applications, dependent: :destroy

  # Validations
  validates :title, presence: true, length: { minimum: 6 }
  validates :overview, presence: true
  validates :responsibilities, presence: true
  validates :requirements, presence: true
  validates :benifits, presence: true
  validates :location, presence: true
  validates :deadline, presence: true
  validates :salary_range, presence: true
  validate :deadline_cannot_be_in_the_past

  private

  def deadline_cannot_be_in_the_past
    if deadline.present? && deadline < Date.today
      errors.add(:deadline, "can't be in the past")
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :set_company, only: %i[ create ]

  # GET /jobs or /jobs.json
  def index
    @pagy, @jobs = pagy(Job.all)
  end

  def my_jobs
    @pagy, @jobs = pagy(Job.where(user_id: current_user.id))
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.build
    @job.company = @company
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = current_user.jobs.build(job_params)
    @job.company = @company

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy!

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :overview, :responsibilities, :requirements, :benifits, :location, :deadline, :salary_range)
    end

    def set_company
      @company = Company.find(current_user.office_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def has_applied(job)
    job.applications.find_by(user_id: current_user.id)
  end

  def can_apply?(job)
    job.deadline > Time.now and current_user.candidate?
  end
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="form-group row">
    <%= form.label :title, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :overview, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :overview, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :responsibilities, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :responsibilities, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :requirements, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :requirements, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :benifits, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_area :benifits, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :location, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :location, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :deadline, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.datetime_field :deadline, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <%= form.label :salary_range, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-10">
      <%= form.text_field :salary_range, class: "form-control" %>
    </div>
  </div>
  <br>
  <div class="form-group row">
    <div class="col-sm-10">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <div class="card-body">
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
          <%= job.title %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Overview</label>
        <div class="col-sm-10">
          <%= job.overview %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Responsibilities</label>
        <div class="col-sm-10">
          <%= job.responsibilities %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Requirements</label>
        <div class="col-sm-10">
          <%= job.requirements %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Benefits</label>
        <div class="col-sm-10">
          <%= job.benifits %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Location</label>
        <div class="col-sm-10">
          <%= job.location %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Salary Range</label>
        <div class="col-sm-10">
          <%= job.salary_range %>
        </div>
      </div>
      <br>
      <div class="form-group row">
        <label class="col-sm-2 col-form-label">Deadline</label>
        <div class="col-sm-10">
          <%= job.deadline %>
        </div>
      </div>
      <br>
    </div>
</div>

app/views/jobs/_job_card.html.erb
<div id="jobs">
  <% @jobs.each_slice(3) do |jobs_group| %>
    <div class="row mb-4">
      <% jobs_group.each do |job| %>
        <div class="col-12 col-md-6 col-lg-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title"><%= job.title %></h5>
              <h6 class="card-subtitle mb-2 text-muted">Location: <%= job.location %></h6>

              <p class="card-text">
                <strong>Salary range:</strong> <%= job.salary_range %><br>
                <strong>Deadline:</strong> <%= job.deadline %><br>
              </p>
              <%= link_to "Show Details", job, class: "btn btn-primary btn-sm" %>
              <% if current_user && job.user_id == current_user.id %>
              <%= link_to "Show Applications", job_applications_path(job), class: "btn btn-info
               btn-sm" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="pagination-container d-flex justify-content-center mt-4">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>

<%= render "job_card" %>

app/views/jobs/my_jobs.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-between">
  <h1>My Jobs</h1>
  <%= link_to "New job opening", new_job_path, class: "btn btn-primary" %>
</div>

<%= render "job_card" %>

app/views/jobs/new.html.erb
<h1>New job opening</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="card">
  <div class="card-body">
    <%= render @job %>
  </div>
  <div class="card-header d-flex">
    <% if current_user == @job.user %>
      <%= link_to "Back to jobs", my_jobs_path, class: "btn btn-sm btn-secondary" %>&nbsp;
      <%= link_to "Edit job", edit_job_path(@job), class: "btn btn-sm btn-warning" %>&nbsp;
      <% if @job.assessment.nil? %>
        <%= link_to "Add Assessment", new_job_assessment_path(@job), class: "btn btn-sm btn-primary" %>&nbsp;
      <% else %>
        <%= link_to "Show Assessment", assessment_path(@job.assessment), class: "btn btn-sm btn-info" %>&nbsp;
      <% end %>
      <%= button_to "Destroy this job", @job, method: :delete, class: "btn btn-sm btn-danger" %>

    <% elsif can_apply?(@job) %>
      <% if has_applied(@job).nil? %>
        <%= link_to "Apply Now", new_job_application_path(@job), class: "btn btn-sm btn-primary" %>
      <% else %>
        <%= link_to "Show Application", application_path(has_applied(@job)), class: "btn btn-sm btn-primary" %>
      <% end %>
  <% end %>
  </div>
</div>